# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: "windows-latest"

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Blazor Project'
  inputs:
    command: build
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
- task: AzureFileCopy@3
  displayName: "Copy the bundle to pwa Storage Accunt"
  inputs:
      SourcePath: "$(Build.ArtifactStagingDirectory)/netstandard2.1/publish/wwwroot"
      azureSubscription: "web-deploy-service-connection"
      Destination: "AzureBlob"
      storage: "pwaappstorage"
      ContainerName: "$web"
