apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: pwa-sample
build:
  artifacts:
  - image: piotrzan/blazorindocker
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - k8s
