---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: pwa-sample
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/Piotr1215/pwa-sample.git

