apiVersion: v1
kind: Service
metadata:
  name: blazorindocker-svc
spec:
  selector:
    app: blazor
  ports:
  - port: 8180
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP