apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorindocker
  labels:
    app: blazor
spec:
  selector:
    matchLabels:
      app: blazor
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blazor
    spec:
      containers:
      - name: blazorindocker
        image: piotrzan/blazorindocker
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
