apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorindocker
  labels:
    app: blazor
spec:
  selector:
    matchLabels:
      app: blazor
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blazor
    spec:
      containers:
      - name: nginx
        image: piotrzan/blazorindocker
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blazorindocker-svc
spec:
  selector:
    app: blazor
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer