apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorindocker
  image: piotrzan/blazorindocker
  labels:
    app: blazor
spec:
  selector:
    matchLabels:
      app: blazor
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blazor
        octopusexport: OctopusExport
      annotations:
        owner: atosik