name: Deploy Website

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v1
      - name: Install surge and fire deployment
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1 # Setup .NET Core
        with:
          dotnet-version: 3.1.300 # Change to your version of .NET Core
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Publish Blazor webassembly using dotnet
      #create Blazor WebAssembly dist output folder in the project directory
        run: dotnet publish -c Release --no-build -o publishoutput # Don't build again, just publish
      - run: npm install -g surge
      - run: surge publishoutput/wwwroot ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}